# Commands to start on workspace startup
tasks:
  - before: curl -s -L https://github.com/wundergraph/wundergraph/releases/download/v0.90.17/wunderctl_0.90.17_Linux_x86_64.tar.gz | tar xzvf - && chmod +x wunderctl && mv wunderctl ./api
    name: "Download Wunderctl"
  - init: npm install
    command: |
      export NEXT_PUBLIC_WG_BASE_URL="https://9991-$GITPOD_WORKSPACE_ID.$GITPOD_WORKSPACE_CLUSTER_HOST"
      export WG_ALLOWED_ORIGIN="https://3000-$GITPOD_WORKSPACE_ID.$GITPOD_WORKSPACE_CLUSTER_HOST"
      echo "$NEXT_PUBLIC_WG_BASE_URL"
      echo "$WG_ALLOWED_ORIGIN"
      npm start
    name: "Start demo"
# Ports to expose on workspace startup
ports:
  - port: 3000
    onOpen: open-preview
    visibility: public
  - port: 9991
    visibility: public
  - port: 4001
    visibility: public
  - port: 4002
    visibility: public
  - port: 4003
    visibility: public
  - port: 4004
    visibility: public

vscode:
  extensions:
    - ms-azuretools.vscode-docker